# Generated by Django 4.1 on 2022-11-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Per',
        ),
    ]
