# Generated by Django 3.2.15 on 2022-11-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_delete_per'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('dob', models.DateField()),
                ('add', models.CharField(max_length=300)),
                ('account', models.CharField(choices=[('C', 'Cheque'), ('D', 'Debit Card'), ('C', 'Credit Card')], max_length=255)),
            ],
        ),
    ]
